version: 1

disable_existing_loggers: False

formatters:
  basic:
    style: '{'
    format: '[{threadName:>14}] {message}'
  simple:
    style: '{'
    format: '{asctime}.{msecs:03.0f} [{threadName:>13}] {levelname}: {name:>8} | {message}'
    datefnt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple 
    stream: ext://sys.stdout

  main_logs_file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: 'log/application.log'

loggers:
  main:
    level: DEBUG
    handlers:
      - console
      - main_logs_file
